### ISSUE TITLE
SteamVR 2.0.8大更新之后无法使用

### ISSUE THREAD

**Issue by YukiTiger** [lixiangwuxian/Hypereal2OpenVR#15]
提示显示屏连接故障，但是能识别到头显、基站、手柄，很离谱| ᐕ)⁾⁾

顺便想问一下怎么赞助大佬 ~(˶‾᷄ꈊ‾᷅˵)~

**Comment by lixiangwuxian** [comment]
https://github.com/lixiangwuxian/Hypereal2OpenVR/releases/tag/prebuild_driver
已经替换了最新的openvr sdk，但是手上没有设备没法测试。

关于赞助，因为目前已经有其它工作，基本抽不出时间来继续完善代码，因此不再接受赞助。十分感谢理解

**Comment by YukiTiger** [comment]
> https://github.com/lixiangwuxian/Hypereal2OpenVR/releases/tag/prebuild_driver 已经替换了最新的openvr sdk，但是手上没有设备没法测试。
> 
> 关于赞助，因为目前已经有其它工作，仅有精力维护正常使用，不能保证抽出足够时间来继续完善功能，因此不再接受赞助。十分感谢理解

ok明白了 谢谢~

**Comment by YukiTiger** [comment]
> https://github.com/lixiangwuxian/Hypereal2OpenVR/releases/tag/prebuild_driver 已经替换了最新的openvr sdk，但是手上没有设备没法测试。
> 
> 关于赞助，因为目前已经有其它工作，仅有精力维护正常使用，不能保证抽出足够时间来继续完善功能，因此不再接受赞助。十分感谢理解

刚刚试了一下，会提示头戴显示器错误：未启用全屏模式，然后VR显示屏是黑的，只好退回上一版本steamvr 1.27测试版。不过还是感谢您抽空更新和回复~ 之后就打算继续换回Oculus了，Hy直接裱框起来23333

**Comment by YukiTiger** [comment]
> https://github.com/lixiangwuxian/Hypereal2OpenVR/releases/tag/prebuild_driver 已经替换了最新的openvr sdk，但是手上没有设备没法测试。
> 
> 关于赞助，因为目前已经有其它工作，仅有精力维护正常使用，不能保证抽出足够时间来继续完善功能，因此不再接受赞助。十分感谢理解

昨晚试了一下0.5.1版本驱动，可以正常配合Hypereal 原驱动使用，只替换手柄没问题。太离谱了

**Comment by lixiangwuxian** [comment]
6，非常符合我对v社的想象

**Comment by lixiangwuxian** [comment]
更新steamvr到2.0.10版本即可
