### ISSUE TITLE
显示黑色纹理

### ISSUE THREAD

**Issue by yangcong666520** [lixiangwuxian/Hypereal2OpenVR#7]
最新版本的驱动在头显中无法显示画面（全黑屏），但可以通过SteamVR的“显示vr视图”看到有渲染的画面

**Comment by lixiangwuxian** [comment]
不知道如何解决，只能临时弄一个[commit](https://github.com/lixiangwuxian/Hypereal2OpenVR/commit/533db90b69f2102eb2af2c739ec3c3cc556f17a6)改回去
