### ISSUE TITLE
无法使用VS 2022编译驱动

### ISSUE THREAD

**Issue by YukiTiger** [lixiangwuxian/Hypereal2OpenVR#8]
> 警告	MSB8004	Output 目录未以斜杠结尾。  此生成实例将添加斜杠，因为必须有这个斜杠才能正确计算 Output 目录。Hypereal_OVRDriver	D:\vs\ide\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets	517	

> 警告	STL4038	The contents of <semaphore> are available only with C++20 or later.	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\semaphore	17	

> 错误	C2039	"counting_semaphore": 不是 "std" 的成员	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	
> 消息		参见“std”的声明	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\queue	26	

> 错误	C2143	语法错误: 缺少“;”(在“<”的前面)	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C2238	意外的标记位于“;”之前	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 警告	STL4038	The contents of <semaphore> are available only with C++20 or later.	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\semaphore	17	

> 错误	C2039	"counting_semaphore": 不是 "std" 的成员	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	
消息		参见“std”的声明	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\queue	26	

> 错误	C2143	语法错误: 缺少“;”(在“<”的前面)	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C2238	意外的标记位于“;”之前	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C2065	“m_pTextureSem”: 未声明的标识符	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\FrameEncoder.cpp	10	

> 错误	C2039	"counting_semaphore": 不是 "std" 的成员	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\FrameEncoder.cpp	10	
消息		参见“std”的声明	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\queue	26	

> 错误	C2061	语法错误: 标识符“counting_semaphore”	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\FrameEncoder.cpp	10	

> 警告	C4244	“=”: 从“double”转换到“float”，可能丢失数据	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\FrameEncoder.cpp	40	

> 错误	C2065	“m_pTextureSem”: 未声明的标识符	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\FrameEncoder.cpp	48	

> 警告	C4244	“参数”: 从“double”转换到“float”，可能丢失数据	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\HYController.cpp	210	

> 警告	C4244	“参数”: 从“double”转换到“float”，可能丢失数据	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\HYController.cpp	211	

> 警告	STL4038	The contents of <semaphore> are available only with C++20 or later.	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\semaphore	17	

> 错误	C2039	"counting_semaphore": 不是 "std" 的成员	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	
消息		参见“std”的声明	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\queue	26	

> 错误	C2143	语法错误: 缺少“;”(在“<”的前面)	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C2238	意外的标记位于“;”之前	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 警告	C4305	“参数”: 从“double”到“float”截断	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\HYHMD.cpp	58	

> 警告	STL4038	The contents of <semaphore> are available only with C++20 or later.	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\semaphore	17	

> 错误	C2039	"counting_semaphore": 不是 "std" 的成员	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	
消息		参见“std”的声明	Hypereal_OVRDriver	D:\vs\ide\VC\Tools\MSVC\14.37.32822\include\queue	26	

> 错误	C2143	语法错误: 缺少“;”(在“<”的前面)	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 错误	C2238	意外的标记位于“;”之前	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\include\FrameEncoder.h	25	

> 警告	C4305	“参数”: 从“double”到“float”截断	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\ServerDriver.cpp	170	

> 警告	C4244	“参数”: 从“int64_t”转换到“int”，可能丢失数据	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\ServerDriver.cpp	223	

> 警告	C4244	“参数”: 从“int64_t”转换到“int”，可能丢失数据	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\source\ServerDriver.cpp	225

**Comment by lixiangwuxian** [comment]
见[在 Visual Studio 开发环境中设置此编译器选项

](https://learn.microsoft.com/zh-cn/cpp/build/reference/std-specify-language-standard-version?view=msvc-170#to-set-this-compiler-option-in-the-visual-studio-development-environment)
语言标准设置为c++20以上

**Comment by YukiTiger** [comment]
>
好的，谢谢！！！

**Comment by YukiTiger** [comment]
> 见[在 Visual Studio 开发环境中设置此编译器选项](https://learn.microsoft.com/zh-cn/cpp/build/reference/std-specify-language-standard-version?view=msvc-170#to-set-this-compiler-option-in-the-visual-studio-development-environment) 语言标准设置为c++20以上

现在可以编译了，然后提示 

> 错误	LNK1181	无法打开输入文件“D:\vs\Project\Hypereal2OpenVR-main\Hypereal2OpenVR-main\libraries\x64\driverlog.lib”	Hypereal_OVRDriver	D:\vs\Project\Hypereal2OpenVR-main\Hypereal2OpenVR-main\LINK	1

**Comment by lixiangwuxian** [comment]
确实我这工程文件上传的有问题，应该是有修改没上传，我等下修改一下

**Comment by lixiangwuxian** [comment]
https://github.com/lixiangwuxian/Hypereal2OpenVR/pull/11
已修改，应该可以编译了

**Comment by lixiangwuxian** [comment]
目前已添加基于Github Action的在线自动编译。
